export const adminReqColumns = [
  {id: "employee", label: "Employee"},
  {id: "projectCode", label: "Project Code"},
  {id: "pickup", label: "Pickup"},
  {id: "drop", label: "Drop"},
  {id: "pickupTime", label: "Pickup Time"},
  {id: "status", label: "Status"},
  {id: "action", label: "Action"},
];

export const adminReqRow = [
  {
    id: 1,
    employee: "Renu",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 2,
    employee: "Sumit",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 3,
    employee: "Renu",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 4,
    employee: "Sumit",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Rejected",
  },
  {
    id: 5,
    employee: "Garima",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 6,
    employee: "Garima",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 7,
    employee: "Garima",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 8,
    employee: "Vikram",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Rejected",
  },
  {
    id: 9,
    employee: "Manisha",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 10,
    employee: "KP",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Rejected",
  },
  {
    id: 11,
    employee: "Khushboo",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 12,
    employee: "KPriya",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Rejected",
  },
  {
    id: 13,
    employee: "Vikram",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 14,
    employee: "Vikram",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Rejected",
  },
  {
    id: 15,
    employee: "Manish",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 16,
    employee: "Manisha",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 17,
    employee: "Vikram",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
  {
    id: 18,
    employee: "Manisha",
    projectCode: "hpb",
    pickup: "42 metro",
    drop: "55-56 metro",
    pickupTime: "9:30",
    status: "Approved",
  },
];

export const employeeReqColumns = [
  {id: "pickup", label: "Pickup"},
  {id: "drop", label: "Drop"},
  {id: "pickupTime", label: "PickupTime"},
  {id: "projectCode", label: "ProjectCode"},
  {id: "status", label: "Status"},
];

export const employeeReqRows = [
  {
    id: 1,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Approved",
  },
  {
    id: 2,
    pickup: "32 avenue",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "zerotech",
    status: "Approved",
  },
  {
    id: 3,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
  {
    id: 4,
    pickup: "sikandarpur",
    drop: "55-56",
    pickupTime: "09:00 am",
    projectCode: "zerotech",
    status: "Rejected",
  },
  {
    id: 5,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "zerotech",
    status: "Approved",
  },
  {
    id: 6,
    pickup: "sikandarpur",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "zerotech",
    status: "Approved",
  },
  {
    id: 7,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
  {
    id: 8,
    pickup: "sikandarpur",
    drop: "55-56",
    pickupTime: "09:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
  {
    id: 9,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Approved",
  },
  {
    id: 10,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "zerotech",
    status: "Approved",
  },
  {
    id: 11,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
  {
    id: 12,
    pickup: "sikandarpur",
    drop: "55-56",
    pickupTime: "09:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
  {
    id: 13,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Approved",
  },
  {
    id: 14,
    pickup: "sikandarpur",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Approved",
  },
  {
    id: 15,
    pickup: "42-43",
    drop: "TW office",
    pickupTime: "10:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
  {
    id: 16,
    pickup: "32 avenue",
    drop: "55-56",
    pickupTime: "09:00 am",
    projectCode: "HPB",
    status: "Rejected",
  },
];
