name: merge main workflow

on:
  push:
    branches: [main, backendSetup]
jobs:
  print:
    name: Printtt
    runs-on: ubuntu-latest
    steps:
      - name: Print env var
        run: |
          echo "1: ${{vars.REACT_APP_BASE_URL}}"
          echo "2: ${{ secrets.REACT_APP_AUTH0_AUDIENCE }}"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Running Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [16.19.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: "Running test"
        run: npm test

  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [16.19.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Running build
        env:
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
          REACT_APP_AUTH0_AUDIENCE: ${{ secrets.REACT_APP_AUTH0_AUDIENCE }}
          REACT_APP_BASE_URL: ${{vars.REACT_APP_BASE_URL}}
        run: npm run build --if-present
      - name: Netlify Deploy
        # uses: jsmrcaga/action-netlify-deploy@v1.7.1

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod
